### ISSUE TITLE
Transformation #1 failed

### ISSUE THREAD

**Issue by casper0078** [dreamnettech/dreamtime#101]
https://rollbar.com/occurrence/uuid/?uuid=412234f6-adf2-4f92-9c6d-df1c90253190

i just pressed to transform the picture and that error appeared 
using os : 8.1 windows  
![3123123](https://user-images.githubusercontent.com/56000418/65910771-a35a9680-e3cb-11e9-971a-fed82782bcd3.png)

**Comment by kolessios** [comment]
Thank you for the report, could you do the following please:

1. Indicate which version of Windows you are using.
2. Copy and paste the text from the "Console" section.

**Comment by casper0078** [comment]
> s\DreamTime\cli\python36.dll'.
 LoadLibrary: The specified module could not be found.

> Error loading Python DLL 'C:\Users\Rizz\AppData\Local\Program
> LoadLibrary: The specified module could not be found.

> Error loading Python DLL 'C:\Users\Rizz\AppData\Local\Programs\DreamTime\cli\python36.dll'.

**Comment by casper0078** [comment]
windows 8.1 pro

**Comment by kolessios** [comment]
The error message indicates that DreamPower was unable to load files necessary for its operation. This is probably caused because your operating system is missing updates or libraries.

This user had a similar problem with another program and also had Windows 8.1, you can try what he said:
https://bitcointalk.org/index.php?topic=2833220.msg29092606#msg29092606

python3.dll or python36.dll must be located in the DreamPower folder. (About -> DreamPower -> App Folder)

**Comment by casper0078** [comment]
i have problem at updating my windows since its cracked version even after i activated it
