### ISSUE TITLE
Vary Image Cropping

### ISSUE THREAD

**Issue by k128** [dreamnettech/dreamtime#113]
Currently on some pictures, a small change in the cropping/resizing makes a huge difference.  I had one photo where it ran well once and then I closed DreamTime and later the same photo came out poorly.  I spent hours trying to match the exact pixels of the first one and finally got it, but a single pixel off and there was a large difference.  

Ideal Solutions:
1. DreamTime analyzes the photo and decides on the best scale and cropping itself
2. OR DreamTime works well on any cropping/scale

Alternate Solutions:
1. More stable results from small changes.  
2. OR Allow the scale and cropping to be set and varied in the preferences tab
3. OR At least allow the user to go back and change the scale or cropping from the current one without having to start all over.

**Comment by kolessios** [comment]
Version 1.1.2 allows you to select among several crop or resizing options, most of them are processed by DreamPower which eliminates the manual crop completely and probably tomorrow DreamPower v1.2.3 will be able to process the manual Crop by itself. 

I close this because I believe that with these options we have fixed the problem of the quality, if the problem persists please open a new issue.
