### ISSUE TITLE
Updated to Dreamtime v1.1.2

### ISSUE THREAD

**Issue by ColoradoExpertta** [dreamnettech/dreamtime#122]
Hi all,

Just updated to v1.1.2 and I am confused.  Has the ability to zoom and pan the original photo disappeard?

Seems like there now is only one choice to do the whole pic, and that is not working very well.

**Comment by kolessios** [comment]
Yes, the previous cropper was replaced by an "overlay" system processed by DreamPower. However, it was a mistake since they are two different systems and the original cropper should not have been replaced. The previous functionality will be restored in v1.1.3 which will be released between today and tomorrow for the [Patrons](https://patreon.com/dreamnet).
