### ISSUE TITLE
Error loading python

### ISSUE THREAD

**Issue by Raso900** [dreamnettech/dreamtime#128]
When I want to start nudify this error appears, please help me!
![1](https://user-images.githubusercontent.com/57471353/70046834-cef92900-1594-11ea-9edd-e39b40f2f0d3.jpg)

**Comment by kolessios** [comment]
By chance your operating system is Windows 8.1? If so, then that problem is something common on that OS, you can try this: https://github.com/dreamnettech/dreamtime/issues/101#issuecomment-536769937

Otherwise it means that some components are missing, maybe it can be fixed when installing Windows updates.
