### ISSUE TITLE
Lineup Assistance

### ISSUE THREAD

**Issue by RigdenYT** [dreamnettech/dreamtime#132]
**Is your feature request related to a problem? Please describe.**
Often the program fails to correctly place features on a given image

**Describe the solution you'd like**
the ability to place certain key points so that the program can more clearly see what it is looking at

**Describe alternatives you've considered**
some sort of 3d model that can be aligned

**Comment by kolessios** [comment]
Could you please be clearer? I can't fully understand what you mean.

I suppose you are trying to say that reference points could be placed in the manual crop to know what position the person's body should be in. If so, for now I cannot consider this improvement due to:

- The algorithm works differently in each photo, placing reference points could work in some photos but not in others.
- Due to the above this could cause more confusion than being a solution.

For now it is best to try several times until you get the best result.

**Comment by kolessios** [comment]
It should also be taken into account that the checkpoints remain the same as those of DeepNude, this means that it is completely normal that most times no decent results are obtained, only the photos that comply with the following are more likely to succeed:

- Only one person should appear in the photo.
- The person is standing in a straight position without crossing arms or legs.
- The person is looking towards the camera.
- The person wears light clothes. Bikinis work better.
- The person's body is visible and unobstructed.
