### ISSUE TITLE
Can’t run properly on Windows 10 

### ISSUE THREAD

**Issue by slickb12** [dreamnettech/dreamtime#171]
Everytime I upload a photo, my program crashes before it finishes. I don’t understand why. If someone could help that’d be great

**Comment by xrebel1** [comment]
DreamTime Requirements; 64-bit OS and 8GB RAM, preferably 16+GB RAM. Check if your system meet these requirements.

**Comment by kolessios** [comment]
The most common cause of this problem is **insufficient RAM**. We recommend a minimum of 8 GB, however due to the problems that some users have presented with that amount it is possible that we raise the minimum to 12 GB. The solutions to this problem are no more than closing all possible programs or buying more RAM.
